# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultisshGo < Formula
  desc ""
  homepage "https://github.com/lcrownover/multissh-go"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.4/multissh-go_0.1.4_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3078fb60299912a917ac11313282f259b1660e4979e88f138b2206cde46a2308"

      def install
        bin.install "multissh-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.4/multissh-go_0.1.4_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4c453bfe975731371767fe60c970dfa839652d2e8229753cf2ac3faab8e5b137"

      def install
        bin.install "multissh-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.4/multissh-go_0.1.4_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "507f232efb5946ec03bedc5c4723cb797e874752c4a6efa9f7c87a39296819f7"

      def install
        bin.install "multissh-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.4/multissh-go_0.1.4_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9be6f0ff11847ccf3dc5972ca3c5954b8bdbbd9a8bbfdac58714c7c1ba4ffd4b"

      def install
        bin.install "multissh-go"
      end
    end
  end
end
