# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultisshGo < Formula
  desc ""
  homepage "https://github.com/lcrownover/multissh-go"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.6/multissh-go_0.1.6_darwin_amd64.tar.gz"
      sha256 "879388f4036baab99549b4b3b0e9f0bfdc8b4b27f0d93b150311a3b643807d80"

      def install
        bin.install "multissh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.6/multissh-go_0.1.6_darwin_arm64.tar.gz"
      sha256 "de5dcbe146d37e499274b5e025b314e922e60cb0632113f07b437b8bae361ef2"

      def install
        bin.install "multissh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.6/multissh-go_0.1.6_linux_amd64.tar.gz"
      sha256 "38694dc758888f25074520af7e048cbdcca6afdf9d0a6acb0681c4b6729cf2d0"

      def install
        bin.install "multissh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.6/multissh-go_0.1.6_linux_arm64.tar.gz"
      sha256 "36b5edf0628d2661d2b7e11954789656f0dafc68b7b7d2f617a2abe82effab4d"

      def install
        bin.install "multissh"
      end
    end
  end
end
