# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultisshGo < Formula
  desc ""
  homepage "https://github.com/lcrownover/multissh-go"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.5/multissh-go_0.1.5_Darwin_arm64.tar.gz", :using => GitDownloadStrategy
      sha256 "28b282ee2e0a744af8e0b14435e48bf761e20ff2c833b6ba11ccacb9b9bd5bc3"

      def install
        bin.install "multissh-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.5/multissh-go_0.1.5_Darwin_x86_64.tar.gz", :using => GitDownloadStrategy
      sha256 "b10474e09343de21b3efa733d6d22a92451bc1ed203738db04fbedef1d35cc4a"

      def install
        bin.install "multissh-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.5/multissh-go_0.1.5_Linux_arm64.tar.gz", :using => GitDownloadStrategy
      sha256 "00a44e5b1d2247a088dbfe985029f64039a9397ef4540302bac34a0a23248e21"

      def install
        bin.install "multissh-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.5/multissh-go_0.1.5_Linux_x86_64.tar.gz", :using => GitDownloadStrategy
      sha256 "5f7928526d1ea4c2c0f1a8681554d90485b7b066609742225ec23061d4be76cf"

      def install
        bin.install "multissh-go"
      end
    end
  end

  depends_on "git"
end
