# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultisshGo < Formula
  desc ""
  homepage "https://github.com/lcrownover/multissh-go"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.1/multissh-go_0.1.1_Darwin_arm64.tar.gz"
      sha256 "13129a3fe3f155075eb1e84d3861479c39d47174275372d179bba8a5e6b1b4e5"

      def install
        bin.install "multissh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.1/multissh-go_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "729587c153fd7657d434082724f53e4116a22daed3dcc1f0b93eb1a265255570"

      def install
        bin.install "multissh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.1/multissh-go_0.1.1_Linux_x86_64.tar.gz"
      sha256 "71a6aa5b3f0a1cb92ec16d04f288ad1187588a259fc386a0a21df54265ed933b"

      def install
        bin.install "multissh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lcrownover/multissh-go/releases/download/v0.1.1/multissh-go_0.1.1_Linux_arm64.tar.gz"
      sha256 "9a3294a783caf4d93ad9e1f1ad5e490830a51d84fdaa5366b190f0244314d284"

      def install
        bin.install "multissh"
      end
    end
  end
end
